# Generated by Django 4.2.11 on 2024-11-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together=set(),
        ),
    ]
