# Generated by Django 4.2.11 on 2024-10-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('can_cancel_order', 'Can cancel an order'), ('can_refund_order', 'Can refund an order'), ('can_ship_order', 'Can ship an order'), ('can_deliver_order', 'Can deliver an order'), ('can_return_order', 'Can return an order')]},
        ),
    ]
