# Generated by Django 4.2.11 on 2024-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
