# Generated by Django 4.2.11 on 2024-11-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_orderdevicemeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REVIEWED', 'Reviewed')], default='REQUESTED', max_length=20, verbose_name='Return Status'),
        ),
    ]
