# Generated by Django 4.2.11 on 2024-11-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_returnrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnlineitem',
            old_name='reason',
            new_name='reason_details',
        ),
        migrations.RenameField(
            model_name='returnrequest',
            old_name='reason',
            new_name='reason_details',
        ),
    ]
