# Generated by Django 4.2.11 on 2024-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_reason_returnlineitem_reason_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnlineitem',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('WRONG_PRODUCT', 'Wrong Product'), ('WRONG_SIZE', 'Wrong Size'), ('WRONG_COLOR', 'Wrong Color'), ('WRONG_VARIANT', 'Wrong Variant'), ('NOT_AS_EXPECTED', 'Not as Expected'), ('NO_REASON', 'No Reason'), ('OTHER', 'Other')], default='NO_REASON', help_text='Reason for the return', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('WRONG_PRODUCT', 'Wrong Product'), ('WRONG_SIZE', 'Wrong Size'), ('WRONG_COLOR', 'Wrong Color'), ('WRONG_VARIANT', 'Wrong Variant'), ('NOT_AS_EXPECTED', 'Not as Expected'), ('NO_REASON', 'No Reason'), ('OTHER', 'Other')], default='NO_REASON', help_text='Reason for the return', max_length=100),
        ),
    ]
