# Generated by Django 4.2.11 on 2024-11-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_returnlineitem_reason_returnrequest_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='intiated_by',
            new_name='initiated_by',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEWED', 'Reviewed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20, verbose_name='Return Status'),
        ),
    ]
