# Generated by Django 4.2.11 on 2024-11-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_intiated_by_returnrequest_initiated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ('-created_at',)},
        ),
    ]
