# Generated by Django 4.2.11 on 2024-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_returnrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnlineitem',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='returnlineitem',
            name='reason_details',
        ),
        migrations.AddField(
            model_name='returnlineitem',
            name='receving_status',
            field=models.CharField(choices=[('not_received', 'Not Received'), ('received', 'Received'), ('received_with_issues', 'Received with Issues')], default='not_received', max_length=20),
        ),
    ]
