# Generated by Django 4.2.11 on 2024-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_returnlineitem_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnlineitem',
            name='receving_status',
            field=models.CharField(choices=[('NOT_RECEIVED', 'Not Received'), ('RECEIVED', 'Received'), ('RECEIVED_WITH_ISSUES', 'Received with Issues')], default='NOT_RECEIVED', max_length=20),
        ),
    ]
