# Generated by Django 4.2.11 on 2024-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_completed_at_returnrequest_resolved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='resolved_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='returnrequest',
            old_name='resolved_by',
            new_name='completed_by',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEWED', 'Reviewed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Resolved')], default='REQUESTED', max_length=20, verbose_name='Return Status'),
        ),
    ]
