# Generated by Django 4.2.11 on 2024-11-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_returnrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email_address',
            new_name='email',
        ),
    ]
