# Generated by Django 4.2.11 on 2024-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_order_total_price_in_customer_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Original amount paid by the customer in the customer's currency, stored in cents. ", max_digits=12, null=True),
        ),
    ]
