# Generated by Django 4.2.11 on 2024-12-05 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_currency_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_without_tax',
            field=models.BigIntegerField(blank=True, help_text='Total amount of the order without tax in cents, stored in the base currency.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
