# Generated by Django 4.2.11 on 2024-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_total_price_without_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('INSUFFICIENT_STOCK', 'Insufficient Stock'), ('NOT_RESERVED', 'Not Reserved')], default='NOT_RESERVED', max_length=20),
        ),
    ]
