# Generated by Django 4.2.11 on 2024-12-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_stockreservation_transferred_to_and_more'),
        ('order', '0029_alter_order_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnlineitem',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Warehouse where the return line item will be received.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse'),
        ),
    ]
