# Generated by Django 4.2.11 on 2025-01-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_currency_alter_order_customer_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('can_approve_order', 'Can approve order'), ('can_cancel_order', 'Can cancel order'), ('can_ship_order', 'Can ship order')]},
        ),
    ]
