# Generated by Django 4.2.11 on 2025-01-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('can_approve_order', 'Can approve order'), ('can_cancel_order', 'Can cancel order'), ('can_ship_order', 'Can ship order'), ('can_process_order', 'Can process order'), ('can_deliver_order', 'Can deliver order'), ('can_update_order_payment_term', 'Can update order payment term'), ('can_update_order_payment_method', 'Can update order payment method')]},
        ),
    ]
