# Generated by Django 4.2.11 on 2025-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0035_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PACKED", "Packed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING_RETURN", "Pending Return"),
                    ("RETURNED", "Returned"),
                ],
                default="PENDING",
                help_text="Represents the current stage of the order within its lifecycle.",
                max_length=20,
                verbose_name="Order Status",
            ),
        ),
    ]
