# Generated by Django 4.2.11 on 2025-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0039_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("RESERVED", "Reserved"),
                    ("RELEASED", "Released"),
                    ("FAILED", "Failed"),
                    ("NOT_REQUIRED", "Not Required"),
                    ("DISPATCHED", "Dispatched"),
                ],
                default="NOT_REQUIRED",
                max_length=20,
            ),
        ),
    ]
