# Generated by Django 4.2.11 on 2024-11-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, help_text='Name of the store.', max_length=100, null=True)),
                ('store_address', models.TextField(blank=True, help_text='Physical address of the store.', null=True)),
                ('city', models.CharField(blank=True, help_text='City of the store.', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country of the store.', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code of the store.', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the site.', null=True, upload_to='logos/')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for site administrators.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number for site administrators.', max_length=20, null=True)),
                ('site', models.OneToOneField(blank=True, help_text='The site this configuration applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
