# Generated by Django 4.2.11 on 2025-02-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_currencyexchange_base_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicesettings",
            name="site",
        ),
    ]
