# Generated by Django 4.2.11 on 2025-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_invoicesettings_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesettings",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="If this is the default invoice settings."
            ),
        ),
    ]
