# Generated by Django 4.2.11 on 2024-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total purchase amount required to use the promo code.', max_digits=10, null=True)),
                ('min_purchase_period', models.DurationField(blank=True, help_text='Time period (e.g., 30 days) within which the minimum purchase amount should be met.', null=True)),
                ('redemption_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promo code can be redeemed.', null=True)),
                ('new_customers_only', models.BooleanField(default=False, help_text='If set, only newly registered customers can use this promo code.')),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single customer can redeem this promo code.')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Promo Code Customer',
                'verbose_name_plural': 'Promo Code Customers',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Promo Code Product',
                'verbose_name_plural': 'Promo Code Products',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the promo code was applied.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
