# Generated by Django 4.2.11 on 2024-10-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.ForeignKey(help_text='The order associated with the use of this promo code.', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promo_code',
            field=models.ForeignKey(help_text='The promo code that was applied to the order.', on_delete=django.db.models.deletion.CASCADE, to='discount.promocode'),
        ),
    ]
