# Generated by Django 4.2.11 on 2024-10-14 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(help_text='Select the customer who redeemed this promo code.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeproduct',
            name='product',
            field=models.ForeignKey(help_text='The product eligible for this promo code.', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='promocodeproduct',
            name='promo_code',
            field=models.ForeignKey(help_text='The promo code that applies to specific products.', on_delete=django.db.models.deletion.CASCADE, to='discount.promocode'),
        ),
        migrations.AddField(
            model_name='promocodecustomer',
            name='customer',
            field=models.ForeignKey(help_text='The customer who is eligible to use this promo code.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodecustomer',
            name='promo_code',
            field=models.ForeignKey(help_text='The promo code that is restricted to specific customers.', on_delete=django.db.models.deletion.CASCADE, to='discount.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Specify products that must be purchased to use the promo code.', related_name='promo_codes', through='discount.PromoCodeProduct', to='product.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='specific_customers',
            field=models.ManyToManyField(blank=True, help_text='Specify users who are eligible for this promo code.', related_name='promo_codes', through='discount.PromoCodeCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeproduct',
            unique_together={('promo_code', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='promocodecustomer',
            unique_together={('promo_code', 'customer')},
        ),
    ]
