# Generated by Django 4.2.11 on 2024-10-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Select the customer who redeemed this promo code.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
