# Generated by Django 4.2.11 on 2024-12-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shippingrate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together=set(),
        ),
    ]
