# Generated by Django 4.2.11 on 2024-10-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions_value',
        ),
    ]
