# Generated by Django 4.2.11 on 2024-10-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productvariant_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('manage_product', 'Can manage product'), ('manage_product_variant', 'Can manage product variant'), ('manage_stock', 'Can manage stock')]},
        ),
    ]
