# Generated by Django 4.2.11 on 2024-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_limit_per_order',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of units that can be purchased in a single order.', null=True),
        ),
    ]
