# Generated by Django 4.2.11 on 2024-11-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productvariant_is_preorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image',
        ),
    ]
