# Generated by Django 4.2.11 on 2024-12-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariant_weight_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='weight_unit',
        ),
    ]
