# Generated by Django 4.2.11 on 2024-12-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_producttype_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Current stock level to show on the storefront or make available for purchase or make some restrictions. the stock value here can be different from the warehouse stock.', verbose_name='Stock'),
        ),
    ]
