# Generated by Django 4.2.11 on 2024-12-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_status',
        ),
    ]
