# Generated by Django 4.2.11 on 2024-12-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productvariant_is_preorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
