# Generated by Django 4.2.11 on 2024-12-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_when_in_relation',
            field=models.CharField(blank=True, help_text="The name used for this product when it is related to another product. For example, if you have a black t-shirt with size variants and a white t-shirt with size variants, you can refer to them as 'black' and 'white' respectively.This field is only used when the product is related to another product.", max_length=255, null=True),
        ),
    ]
