# Generated by Django 4.2.11 on 2026-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productvariant_currency'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_pro_brand_6cdf62_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_live'], name='product_pro_is_live_0d31e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_pro_created_57e07a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='product_pro_price_64133a_idx'),
        ),
    ]
