# Generated by Django 4.2.11 on 2025-12-03 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_reference', models.CharField(max_length=128, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_msisdn', models.CharField(max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('channel', models.CharField(choices=[('mtn-gh', 'MTN Ghana'), ('vodafone-gh', 'Vodafone / Telecel'), ('tigo-gh', 'AirtelTigo')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=16)),
                ('hubtel_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_initial_response', models.JSONField(blank=True, null=True)),
                ('raw_callback_response', models.JSONField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
