# Generated by Django 4.2.11 on 2024-12-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_sku'),
        ('purchase', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant'),
        ),
    ]
