# Generated by Django 4.2.11 on 2024-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaseorderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='rejected_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
