# Generated by Django 4.2.11 on 2024-12-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseorderitem_rejected_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('RECEIVED_AND_CLOSED', 'Received and Closed')], default='DRAFT', max_length=20),
        ),
    ]
