# Generated by Django 4.2.11 on 2024-12-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_name_when_in_relation'),
        ('purchase', '0007_alter_purchaseorder_options_purchaseorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'variant')},
        ),
    ]
