# Generated by Django 4.2.11 on 2025-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='path',
            field=models.FilePathField(allow_folders=True, path='nxtbn\\plugins\\sources/'),
        ),
    ]
