# Generated by Django 4.2.11 on 2025-02-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "permissions": [("CAN_INITIATE_PAYMENT_REFUND", "Can initiate refunds")]
            },
        ),
    ]
