# Generated by Django 4.2.11 on 2025-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_sm",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
