# Generated by Django 4.2.11 on 2025-02-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0003_image_image_sm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_sm",
            new_name="image_xs",
        ),
    ]
