# Generated by Django 4.2.11 on 2025-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0004_rename_image_sm_image_image_xs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_xs",
            field=models.ImageField(blank=True, null=True, upload_to="images/xs/"),
        ),
    ]
