# Generated by Django 4.2.11 on 2024-11-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('STORE_MANAGER', 'Store Manager'), ('PRODUCT_MANAGER', 'Product Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('ORDER_PROCESSOR', 'Order Processor'), ('CUSTOMER_SUPPORT_AGENT', 'Customer Support Agent'), ('ACCOUNTANT', 'Accountant'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=255),
        ),
    ]
