# Generated by Django 4.2.11 on 2025-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('STORE_MANAGER', 'Store Manager'), ('PRODUCT_MANAGER', 'Product Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('ORDER_PROCESSOR', 'Order Processor'), ('CUSTOMER_SUPPORT_AGENT', 'Customer Support Agent'), ('ACCOUNTANT', 'Accountant'), ('VENDOR', 'Vendor'), ('STORE_VIEWER', 'Store Viewer')], default='CUSTOMER', max_length=255),
        ),
    ]
