# Generated by Django 4.2.11 on 2025-02-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_store_admin_user_is_store_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_read_customer", "Can read customer"),
                    ("can_create_customer", "Can update customer"),
                ]
            },
        ),
    ]
