# Generated by Django 4.2.11 on 2024-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reserved',
            field=models.IntegerField(default=0, help_text='Quantity of this product variant that is reserved for specific purposes: 1. Pending Orders: Items reserved for orders that have been placed but not yet fulfilled. 2. Blocked Stock: Inventory set aside for quality control, specific customer allocation, or planned events. 3. Pre-booked Stock: Stock promised to a customer or distributor but not yet shipped.'),
        ),
    ]
