# Generated by Django 4.2.11 on 2024-12-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_reservation_status'),
        ('warehouse', '0006_stockreservation_transferred_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreservation',
            name='transferred_to',
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='order.orderlineitem'),
        ),
    ]
