# Generated by Django 4.2.11 on 2024-12-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_stockreservation_transferred_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='incoming',
            field=models.IntegerField(default=0, help_text='Quantity of this product variant that is expected to arrive because of purchase order or return or transfer'),
        ),
    ]
