# Generated by Django 4.2.11 on 2024-12-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_sku'),
        ('warehouse', '0008_stock_incoming'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('warehouse', 'product_variant')},
        ),
    ]
