# Generated by Django 4.2.11 on 2025-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='rejected_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
