# Generated by Django 4.2.11 on 2025-02-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0011_stocktransfer_created_at_stocktransfer_last_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={
                "permissions": [
                    ("can_receive_transferred_stock", "Can receive transferred stock"),
                    (
                        "can_mark_stock_transfer_as_completed",
                        "Can mark stock transfer as completed",
                    ),
                ]
            },
        ),
    ]
